#!/usr/bin/env python3
"""Tabulate Opus response lengths vs QA bits.

Reads the opus_response_lengths JSON and prints side-by-side tables
comparing baseline bits (tokens × log2(vocab)) against QA bits (10).

Usage:
    python scripts/tabulate_response_lengths.py
    python scripts/tabulate_response_lengths.py --input results/opus_response_lengths/opus_response_lengths_20260126_003935.json
    python scripts/tabulate_response_lengths.py --latex   # output LaTeX table
"""
import argparse
import glob
import json
import os
import numpy as np

BITS_PER_TOKEN = np.log2(100_277)  # 16.61 bits/token
QA_BITS = 10  # all QA sweep problems use exactly 10 yes/no questions

DISPLAY_NAMES = {
    'gsm8k': 'GSM8K',
    'math_algebra': 'MATH (Algebra)',
    'math_geometry': 'MATH (Geometry)',
    'math_number_theory': 'MATH (Num.\\ Theory)',
    'mbpp': 'MBPP',
    'gpqa_mc': 'GPQA (MC)',
    'aime': 'AIME',
    'hle': 'HLE',
}

# Plain-text display names (no LaTeX escaping)
DISPLAY_NAMES_PLAIN = {
    'gsm8k': 'GSM8K',
    'math_algebra': 'MATH (Algebra)',
    'math_geometry': 'MATH (Geometry)',
    'math_number_theory': 'MATH (Num. Theory)',
    'mbpp': 'MBPP',
    'gpqa_mc': 'GPQA (MC)',
    'aime': 'AIME',
    'hle': 'HLE',
}


def load_data(input_path: str) -> dict:
    with open(input_path) as f:
        return json.load(f)


def compute_stats(results: list[dict]) -> dict:
    """Compute token and bit statistics for a set of results."""
    tokens = [r['n_tokens'] for r in results]
    mean_tok = np.mean(tokens)
    std_tok = np.std(tokens)
    mean_bits = mean_tok * BITS_PER_TOKEN
    compression = QA_BITS / mean_bits
    reduction = mean_bits / QA_BITS
    return {
        'n': len(results),
        'mean_tokens': mean_tok,
        'std_tokens': std_tok,
        'mean_bits': mean_bits,
        'compression': compression,
        'reduction': reduction,
    }


def print_detailed_table(data: dict):
    """Print detailed table with per-difficulty breakdown."""
    print(
        f'{"Dataset":<20s} {"Difficulty":<12s} {"n":>4s} {"Tokens":>12s} '
        f'{"Baseline Bits":>14s} {"QA Bits":>8s} {"Ratio":>8s} {"Reduction":>10s}'
    )
    print('-' * 92)

    for ds in data['datasets']:
        name = ds['dataset']
        display = DISPLAY_NAMES_PLAIN.get(name, name)
        results = [r for r in ds['results'] if r['error'] is None]

        for diff in ['medium', 'hard', 'very_hard', 'all']:
            if diff == 'all':
                subset = results
                diff_label = 'ALL'
            else:
                subset = [r for r in results if r['difficulty'] == diff]
                diff_label = diff.replace('_', ' ').title()

            if not subset:
                continue

            stats = compute_stats(subset)
            if diff != 'all':
                tok_str = f'{stats["mean_tokens"]:.0f} ± {stats["std_tokens"]:.0f}'
            else:
                tok_str = f'{stats["mean_tokens"]:.0f}'

            print(
                f'{display:<20s} {diff_label:<12s} {stats["n"]:>4d} {tok_str:>12s} '
                f'{stats["mean_bits"]:>14,.0f} {QA_BITS:>8d} '
                f'{stats["compression"]:>8.4f} {stats["reduction"]:>9.0f}x')

        print()


def print_summary_table(data: dict):
    """Print summary table (all non-easy combined)."""
    print()
    print('=' * 85)
    print('SUMMARY: Opus Response Bits vs QA Bits (all non-easy problems)')
    print('=' * 85)
    print()
    print(
        f'{"Dataset":<20s} {"n":>4s} {"Mean Tokens":>12s} '
        f'{"Baseline Bits":>14s} {"QA Bits":>8s} {"Ratio":>8s} {"Reduction":>10s}'
    )
    print('-' * 80)

    for ds in data['datasets']:
        name = ds['dataset']
        display = DISPLAY_NAMES_PLAIN.get(name, name)
        results = [r for r in ds['results'] if r['error'] is None]
        if not results:
            continue

        stats = compute_stats(results)
        print(f'{display:<20s} {stats["n"]:>4d} {stats["mean_tokens"]:>12.0f} '
              f'{stats["mean_bits"]:>14,.0f} {QA_BITS:>8d} '
              f'{stats["compression"]:>8.4f} {stats["reduction"]:>9.0f}x')


def print_latex_table(data: dict):
    """Print LaTeX table for the paper."""
    print()
    print(r"""% Auto-generated by scripts/tabulate_response_lengths.py
\begin{table}[t]
\centering
\caption{Compression ratios for the QA scheme. Baseline bits encode the full Opus response
using $\text{tokens} \times \log_2(100{,}277)$ bits per token (16.61 bits/token).
QA bits = 10 binary answers. Measured on non-easy problems (medium + hard + very hard).}
\label{tab:qa-compression}
\small
\begin{tabular}{lrrrrl}
\toprule
Dataset & $n$ & Tokens & Baseline Bits & QA Bits & Compression \\
\midrule""")

    for ds in data['datasets']:
        name = ds['dataset']
        display = DISPLAY_NAMES.get(name, name)
        results = [r for r in ds['results'] if r['error'] is None]
        if not results:
            continue

        stats = compute_stats(results)
        tokens_str = f'{stats["mean_tokens"]:.0f}'
        bits_str = f'{stats["mean_bits"]:,.0f}'
        reduction_int = int(round(stats["reduction"]))
        comp_str = f'{stats["compression"]:.4f} ({reduction_int}$\\times$)'
        print(
            f'{display} & {stats["n"]} & {tokens_str} & {bits_str} & {QA_BITS} '
            f'& {comp_str} \\\\')

    print(r"""\bottomrule
\end{tabular}
\end{table}""")


def find_latest_result() -> str:
    """Find the most recent opus_response_lengths JSON file."""
    pattern = 'results/opus_response_lengths/opus_response_lengths_*.json'
    files = sorted(glob.glob(pattern))
    if not files:
        raise FileNotFoundError(f'No files matching {pattern}')
    return files[-1]


def main():
    parser = argparse.ArgumentParser(
        description='Tabulate Opus response lengths vs QA bits')
    parser.add_argument(
        '--input',
        type=str,
        default=None,
        help='Path to opus_response_lengths JSON (default: latest)')
    parser.add_argument('--latex',
                        action='store_true',
                        help='Output LaTeX table for paper')
    parser.add_argument(
        '--summary-only',
        action='store_true',
        help='Only print summary table (no per-difficulty breakdown)')
    args = parser.parse_args()

    input_path = args.input or find_latest_result()
    print(f'Reading: {input_path}')
    print()

    data = load_data(input_path)

    if not args.summary_only:
        print_detailed_table(data)

    print_summary_table(data)

    if args.latex:
        print_latex_table(data)


if __name__ == '__main__':
    main()
